#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.
PATH_TO_FILE=$4
IP=$1
USERNAME=$3
PATH_TO_SSH_KEY=$2

if [ $# -eq 4 ] ; then
    scp -i $PATH_TO_FILE -o StrictHostKeyChecking=no $IP $USERNAME@$PATH_TO_SSH_KEY:
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
