#!/usr/bin/env bash
# Install nginx in an server.

sudo usermod -aG sudo $(whoami)
apt-get -y update
apt-get -y install nginx
rm var/www/html/*
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
