#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update && apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
CONFIG_PATH="/etc/nginx/sites-available/default"
HERE="listen 80 default_server;"
NEW="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/;\n\t}"
sed -i "/$HERE/a\\$NEW" $CONFIG_PATH
service nginx restart
